### PR TITLE
Fix/update bokeh version

### LINKED ISSUE #254: [BUG] Bokeh 2.3 properties are non-nullable by default
ref: http://docs.bokeh.org/en/latest/docs/releases.html#properties-are-non-nullable-by-default

Custom models will require a small update to function:
```
Compilation failed:

../../../../anaconda/envs/rapids-0.18/lib/python3.8/site-packages/cuxfilter/charts/datashader/custom_extensions/graph_inspect_widget.py:CustomInspectTool.ts:12:11 - error TS2322: Type 'boolean | undefined' is not assignable to type 'Boolean'.
  Type 'undefined' is not assignable to type 'Boolean'.

12           this.model._active = this.model.properties.active.spec.value
             ~~~~~~~~~~~~~~~~~~
../../../../anaconda/envs/rapids-0.18/lib/python3.8/site-packages/cuxfilter/charts/datashader/custom_extensions/graph_inspect_widget.py:CustomInspectTool.ts:12:61 - error TS2445: Property 'spec' is protected and only accessible within class 'Property<T>' and its subclasses.

12           this.model._active = this.model.properties.active.spec.value
                                                               ~~~~
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

```

cc @AjayThorve

### PR DESCRIPTION
**Pull request by AjayThorve**
Fixes #254.

Follow up PR will remove support for custom datashader extension and support the much more exhaustive version that holoviews implements

### CODE REVIEW

**Review by ajschmidt8 — COMMENTED** [review]
@AjayThorve, can you also open a PR to update the version below?

https://github.com/rapidsai/integration/blob/branch-21.08/conda/recipes/versions.yaml#L33-L34

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
LGTM I guess there is a solve issue? But it looks unrelated at a glance

**Comment by AjayThorve** [comment]
> @AjayThorve, can you also open a PR to update the version below?
> 
> https://github.com/rapidsai/integration/blob/branch-21.08/conda/recipes/versions.yaml#L33-L34

here you go - https://github.com/rapidsai/integration/pull/308

**Review by ajschmidt8 — APPROVED** [review]

File: ci/gpu/build.sh [hunk 1]
```diff
@@ -59,13 +59,12 @@ gpuci_conda_retry install -y \
...
                "dask-cudf=$MINOR_VERSION.*" "dask-cuda=$MINOR_VERSION.*" \
                "numba>=0.51.2" \
-               "bokeh<=2.2.3" \
                "rapids-build-env=$MINOR_VERSION.*" \
                "rapids-notebook-env=$MINOR_VERSION.*"
 
 # https://docs.rapids.ai/maintainers/depmgmt/ 
-# conda remove -f rapids-build-env rapids-notebook-env
-# conda install "your-pkg=1.0.0"
+conda remove -f rapids-build-env rapids-notebook-env
```
Comment (ajschmidt8) [inline ci/gpu/build.sh:66]:
```suggestion
conda remove --force rapids-build-env rapids-notebook-env
```

whoops. looks like this flag needs to be updated to use `--force` instead of just `-f`.

Comment (AjayThorve) [reply ci/gpu/build.sh:66]: thanks, trying it

File: ci/gpu/build.sh [hunk 2]
```diff
@@ -59,12 +59,13 @@ gpuci_conda_retry install -y \
...
                "dask-cudf=$MINOR_VERSION.*" "dask-cuda=$MINOR_VERSION.*" \
                "numba>=0.51.2" \
+               "bokeh>=2.3.2,<2.4" \
                "rapids-build-env=$MINOR_VERSION.*" \
                "rapids-notebook-env=$MINOR_VERSION.*"
 
 # https://docs.rapids.ai/maintainers/depmgmt/ 
-conda remove --force rapids-build-env rapids-notebook-env
-conda install "bokeh>=2.3.2, <2.4"
+# conda remove -f rapids-build-env rapids-notebook-env
```
Comment (ajschmidt8) [inline ci/gpu/build.sh]:
```suggestion
# conda remove --force rapids-build-env rapids-notebook-env
```

can you update this flag for the next time we have to test?

Comment (AjayThorve) [reply ci/gpu/build.sh]: fixed, thanks!

**Comment by AjayThorve** [comment]
rerun tests

**Comment by AjayThorve** [comment]
@gpucibot merge
